# Generated by Django 4.0.3 on 2022-03-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membersite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(choices=[('L1', '18-19 years old'), ('E2', '20-24 years old'), ('L2', '25-29 years old'), ('E3', '30-34 years old'), ('L3', '35-39 years old'), ('O4', 'more than 40 years old')], default='L1', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], default='M', max_length=1),
        ),
    ]
